name: build

on:
    workflow_call:

env:
    SCCACHE_GHA_ENABLED: "true"

jobs:
    test:
        name: ${{ matrix.name }}
        strategy:
            fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
            matrix:
                include:
                    -   name: Linux-x86_64
                        os: ubuntu-latest
                    -   name: macOS-x86_64
                        os: macOS-latest
                    -   name: macOS-arm64
                        os: macOS-latest
                    -   name: Windows-x86_64
                        os: windows-latest

        runs-on: ${{ matrix.os }}
        steps:
            #A simple printout of the matrix
            -   name: printout
                shell: bash
                run: |
                    echo ${{ github.ref }}
                    echo "matrix.name=${{ matrix.name }}";
                    echo "matrix.os=${{ matrix.os }}";
                    if [ "${{ matrix.name }}" == "Linux-x86_64" ]; then
                        echo "$(uname -a)"
                    elif [ "${{ matrix.os }}" == "macOS-latest" ]; then
                        echo "$(uname -a)"
                    fi;

            # Build the project
            -   name: cmake test
                shell: bash
                run: ctest --test-dir build --output-on-failure -VV
                    